image: atlassian/default-image:2

pipelines:
    branches:
      coral_public:
        - step:
           script:
             - git remote add sync git@github.com:BenMql/coral.git
             - git checkout coral_public
             - git pull
             - git push sync 
