image: atlassian/default-image:2

pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:BenMql/coral.git
             - git checkout master
             - git pull
             - git push sync 
             - git push sync --tags
